apiVersion: v1
kind: Secret
metadata:
  name: example
  namespace: holos-console
  labels:
    app.kubernetes.io/managed-by: console.holos.run
  annotations:
    console.holos.run/share-users: '[{"principal":"admin@example.com","role":"owner"}]'
stringData:
  API_KEY: abc123
  API_URL: https://example.com
type: Opaque
