apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: holos-console-secret-reader
  namespace: holos-console
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-reader
subjects:
  - kind: ServiceAccount
    name: holos-console
    namespace: holos-console
