apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: holos-console
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/holos-run/holos-console.git
    targetRevision: main
    path: deploy
    directory:
      recurse: true
      exclude: argocd/*
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
